spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/myongsik
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        default_batch_fetch_size: 100
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher