spring:
  application:
    name: myongsikMain
  datasource:
    url: ENC(sHx9xyPzq0K9mKUwiRbAhll3qwWlD+60/UyiipBNCRmSlLZI+4ddjKVlNQPD4WUYFk8+qg/BVvRSEVFUKWYxC8aUttkDiysGyp8deZfcIHaoXmnPeEbLeKKBP57gxVYS+oKOVnR7VnM=)
    username: ENC(CdMZ2QjBw5fGW+h2mqmJng==)
    password: ENC(FVfRJV93aIBmq2ZzpHs6iH92Y4HP3Cux)
    driver-class-name: com.mysql.cj.jdbc.Driver