spring:
  application:
    name: myongsikMain

  profiles:
    include:
      secret

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        default_batch_fetch_size: 10
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jasypt:
  encryptor:
    bean: jasyptEncyptor
    encodingType: base64
    algorithm: PBEWithMD5AndDES

#management:
#  endpoint:
#    metrics:
#      enabled: true
#    prometheus:
#      enabled: true
#
#  endpoints:
#    web:
#      exposure:
#        include: health, info, metrics, prometheus
#
#  metrics:
#    tags:
#      application: ${spring.application.name}
---
spring:
  profiles:
    active: prod
---
spring:
  profiles:
    active: dev
---
spring:
  profiles:
    active: local
