spring:
  application:
    name: myongsikMain
  config:
    import:
      - classpath:application-secret.yml
  datasource:
    url: ENC(4etnnfXhOTY+xONvZJ+jHF9tf2ANDIMN7F9+aAlBahfnhllFKLnmdSLiTqEV0O1h)
    username: ENC(QeLUduVvsIAxsBb+5/fwFA==)
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        default_batch_fetch_size: 100
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher



jasypt:
  encryptor:
    bean: jasyptEncyptor

#---
## 현재 프로파일이 prod인 경우, 해당 프로퍼티들을 사용
#spring.config.activate.on-profile: prod
#security.jwt.token.secret-key: "prodKey"
#
#---
## 현재 프로파일이 test인 경우, 해당 프로퍼티들을 사용
#spring.config.activate.on-profile: test
#security.jwt.token.secret-key: "testKey"