spring:
  application:
    name: myongsikMain
  datasource:
    url: ENC(WJ3ygt60c47ky5NU/kSy82Mp+/lnOFKDvrGPVGtKJCZAQRXTTBk17fXy9As1Xys6LXgjA4dKePpD3oA0+oIhDNVwSB30PrHOugaFd9f+FA/FZuJ16fKtOSUup1q1HmAgVLSXocWyKb5mmb1Y2eyOjfZAZMc82Q/2aifOPp47OfbCsWllJiTYkvNCV6R3AmDm)
#    url: ENC(rMxUsofvraIkaMgSRzwu8g6UfnSv1t+I57CAt4Id+qR0Woi/yGJ/dAyT6+KqF/McGN7uSI8aYef1DuWJu13N+1iHbFTfQZbDNalt8A3Lm4MwU0MxUA7o0qf+DU0043KdS8wag3pNGwA=)
    username: ENC(AtyIP2KxL11MVrdq2yBI9Q==)
    password: ENC(dc0+G3VP0z9eZQ+vZZg49KFbrCubCsQj)
    driver-class-name: com.mysql.cj.jdbc.Driver
log:
  config:
    path: /var/log/app
    filename: app-dev
    maxHistory: 3 # 3일
    totalSizeCap: 50MB # 로그 파일 사이즈