spring:
  application:
    name: myongsikMain

  profiles:
    include:
      secret

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
        default_batch_fetch_size: 10
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jasypt:
  encryptor:
    bean: jasyptEncyptor
    encodingType: base64
    algorithm: PBEWithMD5AndDES

---
spring:
  profiles:
    active: prod
---
spring:
  profiles:
    active: dev
---
spring:
  profiles:
    active: local
