global:
  scrape_interval: 10s # 10초마다 매트릭을 수집
  evaluation_interval: 1m # 1분마다 규칙을 평가

  external_labels: # 외부 시스템에 표시할 이 서버의 레이블
    monitor: 'myongsik-monitor'

scrape_configs:
  - job_name: 'monitoring-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080'] # 도커 인스턴스 내부 호스트:8080